version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    # restart: always
    environment:
      - PROJECT_ROOT=/app
    ports:
      - "8080:8080"
  
networks:
  web:
    external: true

